[package]
name        = "yazi-plugin"
version     = "0.1.5"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi plugin system"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-config = { path = "../yazi-config", version = "0.1.5" }
yazi-core   = { path = "../yazi-core", version = "0.1.5" }
yazi-shared = { path = "../yazi-shared", version = "0.1.5" }
mlua          = { version = "^0", features = [ "vendored", "serialize" ] }

# External dependencies
ansi-to-tui   = "^3"
anyhow        = "^1"


ratatui       = "^0"
tracing       = { version = "^0", features = [ "max_level_debug", "release_max_level_warn" ] }
unicode-width = "^0"

[features]
jit = ["mlua/luajit52"]
without-jit = ["mlua/lua52"]
default = ["jit"]
